# Generated by Django 3.1.7 on 2021-03-22 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='final',
            field=models.ImageField(upload_to='media/final/'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField()),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoons.cartoon')),
            ],
        ),
    ]
