# Generated by Django 3.1.7 on 2021-03-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoons', '0002_auto_20210322_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartoon',
            old_name='final',
            new_name='image',
        ),
        migrations.AddField(
            model_name='draft',
            name='image',
            field=models.ImageField(default=False, upload_to='media/draft/'),
            preserve_default=False,
        ),
    ]
